// Pip-Boy / Fallout phosphor green terminal theme
// All inline styles — no CSS files required

export const C = {
    bg:         '#040d04',
    panel:      '#071407',
    border:     '#1e5c1e',
    borderBright: '#2ea82e',
    green:      '#4cfe4c',
    greenDim:   '#267026',
    greenMid:   '#39c439',
    amber:      '#c8ff00',
    muted:      '#2a6e2a',
    red:        '#ff4444',
    font:       "'Courier New', Courier, monospace",
};

export const T = {
    page: {
        background: C.bg,
        color: C.green,
        fontFamily: C.font,
        minHeight: '100vh',
        padding: '0',
    },
    body: {
        maxWidth: '1000px',
        margin: '0 auto',
        padding: '24px 16px',
    },
    h1: {
        color: C.green,
        fontFamily: C.font,
        fontWeight: '700',
        fontSize: '22px',
        letterSpacing: '4px',
        textTransform: 'uppercase',
        textShadow: `0 0 8px ${C.green}`,
        marginBottom: '16px',
        borderBottom: `1px solid ${C.border}`,
        paddingBottom: '8px',
    },
    h2: {
        color: C.greenMid,
        fontFamily: C.font,
        fontWeight: '700',
        fontSize: '14px',
        letterSpacing: '3px',
        textTransform: 'uppercase',
        textShadow: `0 0 6px ${C.greenMid}`,
        marginTop: '24px',
        marginBottom: '10px',
    },
    h3: {
        color: C.green,
        fontFamily: C.font,
        fontWeight: '700',
        fontSize: '14px',
        letterSpacing: '3px',
        textTransform: 'uppercase',
        textShadow: `0 0 6px ${C.green}`,
        marginTop: '0',
        marginBottom: '16px',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
        fontFamily: C.font,
        fontSize: '13px',
        marginTop: '12px',
    },
    th: {
        background: C.panel,
        color: C.greenMid,
        border: `1px solid ${C.border}`,
        padding: '8px 12px',
        textAlign: 'left',
        letterSpacing: '2px',
        textTransform: 'uppercase',
        fontSize: '11px',
    },
    td: {
        border: `1px solid ${C.border}`,
        padding: '7px 12px',
        color: C.green,
        background: 'transparent',
    },
    tdAlt: {
        border: `1px solid ${C.border}`,
        padding: '7px 12px',
        color: C.green,
        background: '#050f05',
    },
    trHover: {
        background: '#0a200a',
        cursor: 'pointer',
    },
    btn: {
        fontFamily: C.font,
        fontSize: '12px',
        fontWeight: '700',
        letterSpacing: '1px',
        textTransform: 'uppercase',
        background: 'transparent',
        color: C.green,
        border: `1px solid ${C.green}`,
        padding: '5px 12px',
        cursor: 'pointer',
        textShadow: `0 0 4px ${C.green}`,
        boxShadow: `0 0 4px ${C.greenDim}`,
        transition: 'all 0.1s',
    },
    btnDanger: {
        fontFamily: C.font,
        fontSize: '12px',
        fontWeight: '700',
        letterSpacing: '1px',
        textTransform: 'uppercase',
        background: 'transparent',
        color: C.red,
        border: `1px solid ${C.red}`,
        padding: '5px 12px',
        cursor: 'pointer',
        transition: 'all 0.1s',
    },
    input: {
        fontFamily: C.font,
        fontSize: '13px',
        background: '#020902',
        color: C.green,
        border: `1px solid ${C.border}`,
        padding: '5px 8px',
        outline: 'none',
        width: '220px',
        caretColor: C.green,
    },
    select: {
        fontFamily: C.font,
        fontSize: '13px',
        background: '#020902',
        color: C.green,
        border: `1px solid ${C.border}`,
        padding: '5px 8px',
        outline: 'none',
        width: '238px',
    },
    label: {
        color: C.greenMid,
        fontFamily: C.font,
        fontSize: '12px',
        letterSpacing: '1px',
        textTransform: 'uppercase',
        display: 'block',
        marginBottom: '4px',
    },
    fieldWrap: {
        marginBottom: '14px',
    },
    modal: {
        position: 'fixed',
        top: '15%',
        left: '50%',
        transform: 'translateX(-50%)',
        background: C.panel,
        border: `1px solid ${C.borderBright}`,
        boxShadow: `0 0 24px ${C.greenDim}, inset 0 0 40px rgba(0,0,0,0.6)`,
        padding: '28px 32px',
        zIndex: 100,
        minWidth: '340px',
        fontFamily: C.font,
    },
    overlay: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.7)',
        zIndex: 99,
    },
    error: {
        fontFamily: C.font,
        fontSize: '12px',
        color: C.red,
        border: `1px solid ${C.red}`,
        padding: '8px 12px',
        marginBottom: '12px',
        letterSpacing: '1px',
    },
    muted: {
        color: C.muted,
        fontFamily: C.font,
        fontSize: '12px',
        letterSpacing: '1px',
    },
    divider: {
        border: 'none',
        borderTop: `1px solid ${C.border}`,
        margin: '20px 0',
    },
    subTable: {
        width: '100%',
        borderCollapse: 'collapse',
        fontFamily: C.font,
        fontSize: '12px',
        marginTop: '8px',
    },
    subTd: {
        border: `1px solid ${C.greenDim}`,
        padding: '5px 10px',
        color: C.greenMid,
    },
    subTh: {
        background: '#030c03',
        color: C.muted,
        border: `1px solid ${C.greenDim}`,
        padding: '5px 10px',
        textAlign: 'left',
        fontSize: '10px',
        letterSpacing: '2px',
        textTransform: 'uppercase',
    },
    expandedRow: {
        background: '#030c03',
        borderLeft: `2px solid ${C.borderBright}`,
        padding: '16px 20px',
    },
};
